new es operator
kudobuilder/frameworks pull request #138
Opened 2019-11-29 06:55 UTC by ruguodangshi

### 添加一个新的operator，使用自定的的es镜像，es版本为2.4.1
使用2.4.1版本es的原始是这个版本在公司线上环境使用的最多，目前还没有升级到新版本。
该operator有如下的特点：
- 使用自定义的镜像
- 使用localPv作为es的存储
- 固定master节点数为3
- 支持自定义data节点数，默认为1（取决于nodeNum这个参数，data节点数等于nodeNum-3）

2019-12-05 16:21 UTC, zmalik requested changes
Thanks @ruguodangshi ! 
PR looks good to start with, we are working on having a `CONTRIBUTING.md` to help new contributors to start with new operators. 
As for now, I have left a few comments for the PR.

2019-12-05 16:21 UTC, zmalik commented on repository/elasticsearch-v2.4.1/docs/README.md
> +The image used in the operator has been passed to my own dockerhub repository，tag is "ruguodangshi/elasticsearch-unicom:2.4.1".
can you add a link to the `Dockerfile` in the documentation?

2019-12-05 16:21 UTC, zmalik commented on repository/elasticsearch-v2.4.1/operator/params.yaml
> +    default: "local-storage"
`local-storage` can be risky for the users, unless a complete graceful strategy is defined.
Let's use the default storage class by default and still give users an option to specify the storage class name if they don't want the default storage class.

2019-12-05 16:21 UTC, zmalik commented on repository/elasticsearch-v2.4.1/operator/templates/statefulset.yaml
> +kind: Service
let's move `Service` objects to a separate `service.yaml` in `templates`

2019-12-05 16:21 UTC, zmalik commented on repository/elasticsearch-v2.4.1/operator/templates/statefulset.yaml
> +      - name: time       #跟上面的名称对应
let's add the comments in English

2019-12-05 19:32 UTC, meichstedt commented
@ruguodangshi is there any particular reason why you added an additional ES operator? What about improving the existing one [here](https://github.com/kudobuilder/operators/tree/master/repository/elastic)?

2019-12-06 02:06 UTC, ruguodangshi commented on repository/elasticsearch-v2.4.1/docs/README.md
> +The image used in the operator has been passed to my own dockerhub repository，tag is "ruguodangshi/elasticsearch-unicom:2.4.1".
thanks!
I will close this pr and submit a new one.

2019-12-06 02:06 UTC, closed without merging