Use kudo from master
kudobuilder/frameworks pull request #55
Opened 2019-07-25 22:52 UTC by jbarrick-mesosphere

2019-07-25 22:53 UTC, jbarrick-mesosphere commented
Once I get the CLI testing implementation in we shouldn't need this makefile at all.

2019-07-25 23:17 UTC, jbarrick-mesosphere commented
>             case.go:105: resource StatefulSet:kudo-test-adjusted-tomcat/zk-zookeeper: .status.readyReplicas: value mismatch: 3 != 2

Let's bump the timeout.

2019-07-26 09:27 UTC, alenkacz requested changes
I am not sure we should use master for testing operators. Right now it's a turbulent times and we're breaking things but I think until we release stable version, people should be developing operators against that stable version.

2019-07-26 13:10 UTC, kensipe approved these changes
I agree we are breaking things and we shouldn't stop... however I also agree we should test against master at some frequency and have early feedback that the operators are broken with master.   That testing should probably be switched and be in kudo testing operators.   This repo should probably be test against the latest release.

Ideally... PRs for operators should be run against 2 kudo versions.  
1. currently release with a failure stopping a PR
2. against master with pass/fall providing info (or just a warning).   Not PR stopping.

2019-07-26 13:10 UTC, kensipe commented on .gitignore
> -go.sum
I'm not sure we want this... we definitely do not want a run of a test to create a "dirty" env.

2019-07-26 13:52 UTC, alenkacz commented
Agreed Ken that we need these tests, I just don't feel the operators repo should by default point to master. We should have pipeline testing master against operators, but us breaking master in KUDO should not break operators repo (yesterday we discussed that, we don't guarantee master being stable - master can break any time, breakage of master should not mean that people cannot integrate into this repo)

2019-07-26 16:42 UTC, jbarrick-mesosphere commented
Closing this one out - 0.4.0 release happens on Monday which will allow us to fix CI.

2019-07-26 16:42 UTC, closed without merging