Kafka upgrade docs refreshed
kudobuilder/frameworks pull request #64
Opened 2019-08-06 13:22 UTC by alenkacz

2019-08-06 13:45 UTC, zmalik requested changes
thank you @alenkacz ! 
LGTM just leaving two suggestions

2019-08-06 13:45 UTC, zmalik commented on repository/kafka/docs/v0.2/upgrade.md
> +The following upgrade procedure assumes one running Kafka cluster and one Kafka operator version already installed (version `kafka-0.1.1`). It also assumes one is running KUDO 0.5.0:
```suggestion
The following upgrade procedure assumes one running Kafka cluster and one Kafka operator version already installed (version `kafka-0.1.1`). It also assumes one is running KUDO 0.5.0 or later:
```

2019-08-06 13:45 UTC, zmalik commented on repository/kafka/docs/v0.2/upgrade.md
> +Upgrade operator version from current to 0.2.0:
can you remove the above line or merge into this one? as right now it is:
```
To update the Kafka cluster from version `0.1.1` to `0.2.0`:

Upgrade operator version from current to 0.2.0:
```

2019-08-07 07:21 UTC, alenkacz commented
@zmalik done :)

2019-08-07 07:58 UTC, zmalik approved these changes
LGTM! Thanks a lot @alenkacz

2019-08-07 08:24 UTC, merged